### ISSUE TITLE
Questions about choosing a replication strategy

### ISSUE THREAD

**Issue by salzhrani** [ipfs/research-CRDT#39]
Would appreciate your feedback on figuring out the best approach for collaborative editing on JSON documents.

I am hoping to add collaborative editing to a project I am working on, which currently uses websockets to send diffs generated by [jsondiffpatch](https://github.com/benjamine/jsondiffpatch) to the backend where it applies the diff and stores the result. and no concurrent editing even by the same user.

I have looked at [A Conflict-Free Replicated JSON Datatype](https://arxiv.org/pdf/1608.03960.pdf) and `automerge`, and I don't think they are a good fit for the reasons mentioned by @pgte in his explanation. In addition, most CRDTs assume that nodes are peers which is not accurate in client-server apps.

δ-CRDTs seem to be a better fit, especially that it can support nested Maps of δ-CRDTs but the scientific jargon in the paper is very challenging for me. I was glad to find @pgte implementation that might help me understand somewhat the algorithms.

Ideally, editing should be confined to sessions, and all the metadata needed for replication should be attached to that session. by that, I mean once a user decides to edit a document a session is started and the metadata needed for replication is generated, and a user or more collaborate on a document. Once all users leave the session, all metadata is purged. sessions can tolerate partitions to a point (eg: n-hours) after which the rejoining node loses any guarantees to continue editing seamlessly.

so given my use case, which approach it best? CRDTs? ad-hoc logic?

**Comment by pgte** [comment]
@salzhrani I’m curious, why do you think JSON-CRDT is not a good fit?

**Comment by salzhrani** [comment]
I think mainly due to the lack of garbage collection and maybe how automerge is implemented. I might be wrong

**Comment by pgte** [comment]
@salzhrani Ha, ok. That's more of a general problem regarding op-based CRDTs and not JSON-CRDT itself.

It feels like you're looking for a [delta-based](http://haslab.uminho.pt/ashoker/files/deltacrdt.pdf) JSON CRDT, where, instead of mutators, you have delta-mutators that return __a representation of the effect__ (instead of an operation). If one doesn't exist (I don't know any) you could try to create one based on the op-based one. I would start that by [understanding the JSON-CRDT internals](https://github.com/ipfs/research-CRDT/blob/master/research/json-crdt.md) and understanding [delta-CRDTs](http://haslab.uminho.pt/ashoker/files/deltacrdt.pdf).

If that sounds too complicated, I would start by using [automerge](https://github.com/automerge/automerge) and see where that takes you.

I definitely don't recommend doing doing ad-hoc logic, as you would want to prove that it converges no matter the order of the messages. And, in doing that, you would probably be redoing a version of the JSON-CRDT type...

@salzhrani does this answer your question?

**Comment by salzhrani** [comment]
Yes, thank you.

if there was to be an implementation that uses delta-mutators instead of ops, what would an overview of it look like if it is possible to say?

**Comment by pgte** [comment]
I don't know the exact internals of the JSON-CRDT, but, according to the delta-CRDT spec, a delta-mutator returns a minimal version of the state, enough to represent the change but not more. This delta is not an operation, as it has to be idempotent. So you will need to know and understand the internal state of the JSON CRDT to understand how to best define a delta.

**Comment by salzhrani** [comment]
I am experimenting with automerge until it or something else gets better.

Thanks
